name: Release Arch OS Manager

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Environment
        run: echo "SNAPSHOT_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Rename binary
        run: mv ./arch-os ./arch-os-${{ env.SNAPSHOT_VERSION }}.sh

      - name: Upload Arch OS Manager to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./arch-os-${{ env.SNAPSHOT_VERSION }}.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
